export type HttpStatusCode = {
  code: number
  name: string
  description: string
  type: 'HTTP' | 'WebDav'
};

export type HttpStatusCodeCategory = {
  category: string
  codes: HttpStatusCode[]
};

export const codesByCategoriesZh: HttpStatusCodeCategory[] = [
  {
    category: '1xx 信息性响应',
    codes: [
      {
        code: 100,
        name: '继续',
        description: '等待客户端发送请求体。',
        type: 'HTTP',
      },
      {
        code: 101,
        name: '切换协议',
        description: '服务器已同意切换协议。',
        type: 'HTTP',
      },
      {
        code: 102,
        name: '处理中',
        description: '服务器正在处理请求，但尚未返回响应。',
        type: 'WebDav',
      },
      {
        code: 103,
        name: '早期提示',
        description: '服务器在最终 HTTP 消息之前返回部分响应头。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '2xx 成功',
    codes: [
      {
        code: 200,
        name: '成功 (OK)',
        description: '成功 HTTP 请求的标准响应。',
        type: 'HTTP',
      },
      {
        code: 201,
        name: '已创建',
        description: '请求已成功处理，并创建了一个新资源。',
        type: 'HTTP',
      },
      {
        code: 202,
        name: '已接受',
        description: '请求已被接受处理，但处理尚未完成。',
        type: 'HTTP',
      },
      {
        code: 203,
        name: '非权威信息',
        description: '请求成功，但原始请求内容已被转换代理修改。',
        type: 'HTTP',
      },
      {
        code: 204,
        name: '无内容',
        description: '服务器已成功处理请求，未返回任何内容。',
        type: 'HTTP',
      },
      {
        code: 205,
        name: '重置内容',
        description: '服务器指示重新初始化发送此请求的文档视图。',
        type: 'HTTP',
      },
      {
        code: 206,
        name: '部分内容',
        description: '由于客户端发送了范围（Range）请求头，服务器仅返回资源的一部分。',
        type: 'HTTP',
      },
      {
        code: 207,
        name: '多状态',
        description: '随后的消息体是一个 XML 消息，可包含多个独立的响应码。',
        type: 'WebDav',
      },
      {
        code: 208,
        name: '已报告',
        description: 'DAV 绑定的成员已在（多状态）响应的前面部分中枚举过。',
        type: 'WebDav',
      },
      {
        code: 226,
        name: '已使用 IM',
        description: '服务器已完成对资源的请求，响应是该结果的表示。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '3xx 重定向',
    codes: [
      {
        code: 300,
        name: '多种选择',
        description: '表示客户端可选择的资源的多个选项。',
        type: 'HTTP',
      },
      {
        code: 301,
        name: '永久移动',
        description: '当前及以后所有请求都应定向到给定的 URI。',
        type: 'HTTP',
      },
      {
        code: 302,
        name: '临时重定向 (Found)',
        description: '重定向到另一个 URL。这是行业实践与标准相冲突的一个例子。',
        type: 'HTTP',
      },
      {
        code: 303,
        name: '查看其它',
        description: '请求的响应可以通过另一个 URI 使用 GET 方法获取。',
        type: 'HTTP',
      },
      {
        code: 304,
        name: '未修改',
        description: '表示自请求头中指定的版本以来，资源未被修改。',
        type: 'HTTP',
      },
      {
        code: 305,
        name: '使用代理',
        description: '所请求的资源仅能通过代理访问，代理地址在响应中提供。',
        type: 'HTTP',
      },
      {
        code: 306,
        name: '切换代理',
        description: '不再使用。最初含义为“后续请求应使用指定的代理”。',
        type: 'HTTP',
      },
      {
        code: 307,
        name: '临时重定向',
        description: '在此情况下应使用另一个 URI 重复请求；但以后的请求仍应使用原始 URI。',
        type: 'HTTP',
      },
      {
        code: 308,
        name: '永久重定向',
        description: '请求及以后所有请求都应使用另一个 URI 重复。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '4xx 客户端错误',
    codes: [
      {
        code: 400,
        name: '错误请求',
        description: '由于明显的客户端错误，服务器无法或不愿处理该请求。',
        type: 'HTTP',
      },
      {
        code: 401,
        name: '未授权',
        description: '类似于 403 禁止，但专门用于需要身份验证且验证失败或尚未提供的情况。',
        type: 'HTTP',
      },
      {
        code: 402,
        name: '需要付款',
        description: '为将来使用而保留。最初意图是该状态码可能用于某种形式的数字现金或小额支付方案。',
        type: 'HTTP',
      },
      {
        code: 403,
        name: '禁止',
        description: '请求有效，但服务器拒绝执行操作。用户可能不具备访问某资源所需的权限。',
        type: 'HTTP',
      },
      {
        code: 404,
        name: '未找到',
        description: '无法找到所请求的资源，但将来可能可用。',
        type: 'HTTP',
      },
      {
        code: 405,
        name: '方法不允许',
        description: '请求的资源的请求方法不被支持。',
        type: 'HTTP',
      },
      {
        code: 406,
        name: '不可接受',
        description: '根据请求中发送的 Accept 头，所请求的资源只能生成不可接受的内容。',
        type: 'HTTP',
      },
      {
        code: 407,
        name: '需要代理认证',
        description: '客户端必须先通过代理进行身份验证。',
        type: 'HTTP',
      },
      {
        code: 408,
        name: '请求超时',
        description: '服务器等待请求时发生超时。',
        type: 'HTTP',
      },
      {
        code: 409,
        name: '冲突',
        description: '由于请求中的冲突（如编辑冲突），请求无法被处理。',
        type: 'HTTP',
      },
      {
        code: 410,
        name: '已删除',
        description: '表示所请求的资源不再可用，并且将来也不会再可用。',
        type: 'HTTP',
      },
      {
        code: 411,
        name: '需要内容长度',
        description: '请求未指定其内容长度，而该长度是被请求资源所要求的。',
        type: 'HTTP',
      },
      {
        code: 412,
        name: '前提条件失败',
        description: '服务器不满足请求者对该请求设置的前提条件之一。',
        type: 'HTTP',
      },
      {
        code: 413,
        name: '负载过大',
        description: '请求大小超过了服务器愿意或能够处理的范围。',
        type: 'HTTP',
      },
      {
        code: 414,
        name: 'URI 过长',
        description: '提供的 URI 过长，服务器无法处理。',
        type: 'HTTP',
      },
      {
        code: 415,
        name: '不支持的媒体类型',
        description: '请求实体的媒体类型不被服务器或资源支持。',
        type: 'HTTP',
      },
      {
        code: 416,
        name: '请求范围不满足',
        description: '客户端请求了文件的一部分，但服务器无法提供该部分。',
        type: 'HTTP',
      },
      {
        code: 417,
        name: '预期失败',
        description: '服务器无法满足 Expect 请求头字段的要求。',
        type: 'HTTP',
      },
      {
        code: 418,
        name: '我是一个茶壶',
        description: '服务器拒绝用茶壶煮咖啡的尝试。',
        type: 'HTTP',
      },
      {
        code: 421,
        name: '错误定向的请求',
        description: '请求被定向到了一个无法产生响应的服务器。',
        type: 'HTTP',
      },
      {
        code: 422,
        name: '不可处理的实体',
        description: '请求格式正确，但由于语义错误而无法执行。',
        type: 'HTTP',
      },
      {
        code: 423,
        name: '已锁定',
        description: '正在访问的资源已被锁定。',
        type: 'WebDav',
      },
      {
        code: 424,
        name: '依赖失败',
        description: '由于前一个请求失败，导致本次请求失败。',
        type: 'WebDav',
      },
      {
        code: 425,
        name: '过早',
        description: '表示服务器不愿意处理可能重放的请求。',
        type: 'HTTP',
      },
      {
        code: 426,
        name: '需要升级',
        description: '客户端应切换到不同的协议，例如 TLS/1.0。',
        type: 'HTTP',
      },
      {
        code: 428,
        name: '需要前提条件',
        description: '原始服务器要求请求是条件性的。',
        type: 'HTTP',
      },
      {
        code: 429,
        name: '请求过多',
        description: '用户在给定时间内发送了过多请求。',
        type: 'HTTP',
      },
      {
        code: 431,
        name: '请求头字段过大',
        description: '服务器不愿意处理请求，因为单个头字段或所有头字段整体过大。',
        type: 'HTTP',
      },
      {
        code: 451,
        name: '因法律原因不可用',
        description: '服务器运营者收到法律要求，拒绝访问包含所请求资源在内的一组资源。',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '5xx 服务器错误',
    codes: [
      {
        code: 500,
        name: '服务器内部错误',
        description: '当遇到意外情况且无更具体信息时给出的通用错误消息。',
        type: 'HTTP',
      },
      {
        code: 501,
        name: '未实现',
        description: '服务器要么无法识别请求方法，要么缺乏完成请求的能力。',
        type: 'HTTP',
      },
      {
        code: 502,
        name: '网关错误',
        description: '服务器作为网关或代理时，从上游服务器收到了无效响应。',
        type: 'HTTP',
      },
      {
        code: 503,
        name: '服务不可用',
        description: '服务器当前不可用（因为过载或停机维护）。',
        type: 'HTTP',
      },
      {
        code: 504,
        name: '网关超时',
        description: '服务器作为网关或代理时，未能及时从上游服务器收到响应。',
        type: 'HTTP',
      },
      {
        code: 505,
        name: '不支持的 HTTP 版本',
        description: '服务器不支持请求中使用的 HTTP 协议版本。',
        type: 'HTTP',
      },
      {
        code: 506,
        name: '变体也在协商',
        description: '对请求的透明内容协商导致了循环引用。',
        type: 'HTTP',
      },
      {
        code: 507,
        name: '存储空间不足',
        description: '服务器无法存储完成请求所需的表示。',
        type: 'WebDav',
      },
      {
        code: 508,
        name: '检测到循环',
        description: '服务器在处理请求时检测到无限循环。',
        type: 'WebDav',
      },
      {
        code: 510,
        name: '未扩展',
        description: '服务器需要满足请求的进一步扩展。',
        type: 'HTTP',
      },
      {
        code: 511,
        name: '需要网络认证',
        description: '客户端需要进行身份验证才能获得网络访问权限。',
        type: 'HTTP',
      },
    ],
  },
];

export const codesByCategoriesEn: HttpStatusCodeCategory[] = [
  {
    category: '1xx Informational responses',
    codes: [
      {
        code: 100,
        name: 'Continue',
        description: 'Server acknowledges the request headers and asks the client to send the request body.',
        type: 'HTTP',
      },
      {
        code: 101,
        name: 'Switching Protocols',
        description: 'Server has agreed to switch protocols as requested by the client (e.g. to WebSocket).',
        type: 'HTTP',
      },
      {
        code: 102,
        name: 'Processing',
        description: 'Server is processing the request but no response is available yet.',
        type: 'WebDav',
      },
      {
        code: 103,
        name: 'Early Hints',
        description: 'Server returns some response headers before the final HTTP message.',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '2xx Success',
    codes: [
      {
        code: 200,
        name: 'OK',
        description: 'Standard response for a successful HTTP request.',
        type: 'HTTP',
      },
      {
        code: 201,
        name: 'Created',
        description: 'The request has succeeded and a new resource has been created.',
        type: 'HTTP',
      },
      {
        code: 202,
        name: 'Accepted',
        description: 'The request has been accepted for processing, but processing is not yet complete.',
        type: 'HTTP',
      },
      {
        code: 203,
        name: 'Non-Authoritative Information',
        description: 'The request succeeded but the content was modified by a transforming proxy.',
        type: 'HTTP',
      },
      {
        code: 204,
        name: 'No Content',
        description: 'The server successfully processed the request and returns no content.',
        type: 'HTTP',
      },
      {
        code: 205,
        name: 'Reset Content',
        description: 'The server asks the client to reset the document view that sent this request.',
        type: 'HTTP',
      },
      {
        code: 206,
        name: 'Partial Content',
        description: 'The server delivers only part of the resource due to a Range request header.',
        type: 'HTTP',
      },
      {
        code: 207,
        name: 'Multi-Status',
        description: 'The body is an XML message that can contain multiple independent status codes.',
        type: 'WebDav',
      },
      {
        code: 208,
        name: 'Already Reported',
        description: 'Members of a DAV binding have already been enumerated in a previous part of the response.',
        type: 'WebDav',
      },
      {
        code: 226,
        name: 'IM Used',
        description: 'The server has fulfilled the request and the response is a representation of the result.',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '3xx Redirection',
    codes: [
      {
        code: 300,
        name: 'Multiple Choices',
        description: 'Indicates multiple options for the resource that the client may choose from.',
        type: 'HTTP',
      },
      {
        code: 301,
        name: 'Moved Permanently',
        description: 'The resource and all future requests should be directed to the given URI.',
        type: 'HTTP',
      },
      {
        code: 302,
        name: 'Found',
        description: 'Redirect to another URL. A known conflict between industry practice and the standard.',
        type: 'HTTP',
      },
      {
        code: 303,
        name: 'See Other',
        description: 'The response can be fetched via GET at another URI.',
        type: 'HTTP',
      },
      {
        code: 304,
        name: 'Not Modified',
        description: 'Indicates the resource has not been modified since the version specified in the request headers.',
        type: 'HTTP',
      },
      {
        code: 305,
        name: 'Use Proxy',
        description: 'The requested resource is only reachable via the proxy given in the response.',
        type: 'HTTP',
      },
      {
        code: 306,
        name: 'Switch Proxy',
        description: 'No longer used. Originally meant "subsequent requests should use the specified proxy".',
        type: 'HTTP',
      },
      {
        code: 307,
        name: 'Temporary Redirect',
        description: 'The request should be repeated with another URI, but future requests should still use the original URI.',
        type: 'HTTP',
      },
      {
        code: 308,
        name: 'Permanent Redirect',
        description: 'The request and all future requests should be repeated using another URI.',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '4xx Client errors',
    codes: [
      {
        code: 400,
        name: 'Bad Request',
        description: 'The server cannot or will not process the request due to an apparent client error.',
        type: 'HTTP',
      },
      {
        code: 401,
        name: 'Unauthorized',
        description: 'Similar to 403, but specifically for authentication that is required and failed or was not provided.',
        type: 'HTTP',
      },
      {
        code: 402,
        name: 'Payment Required',
        description: 'Reserved for future use. Originally intended for some form of digital cash or micro-payment.',
        type: 'HTTP',
      },
      {
        code: 403,
        name: 'Forbidden',
        description: 'The request was valid but the server refuses to act. The user may lack the necessary permissions.',
        type: 'HTTP',
      },
      {
        code: 404,
        name: 'Not Found',
        description: 'The requested resource could not be found but may be available in the future.',
        type: 'HTTP',
      },
      {
        code: 405,
        name: 'Method Not Allowed',
        description: 'The request method is not supported for the requested resource.',
        type: 'HTTP',
      },
      {
        code: 406,
        name: 'Not Acceptable',
        description: 'The resource can only generate content not acceptable per the Accept header sent.',
        type: 'HTTP',
      },
      {
        code: 407,
        name: 'Proxy Authentication Required',
        description: 'The client must first authenticate with the proxy.',
        type: 'HTTP',
      },
      {
        code: 408,
        name: 'Request Timeout',
        description: 'The server timed out while waiting for the request.',
        type: 'HTTP',
      },
      {
        code: 409,
        name: 'Conflict',
        description: 'The request could not be processed because of a conflict (e.g. an edit conflict).',
        type: 'HTTP',
      },
      {
        code: 410,
        name: 'Gone',
        description: 'The requested resource is no longer available and will not be available again.',
        type: 'HTTP',
      },
      {
        code: 411,
        name: 'Length Required',
        description: 'The request did not specify its length, which is required by the resource.',
        type: 'HTTP',
      },
      {
        code: 412,
        name: 'Precondition Failed',
        description: 'The server does not meet one of the preconditions the requester set.',
        type: 'HTTP',
      },
      {
        code: 413,
        name: 'Payload Too Large',
        description: 'The request is larger than the server is willing or able to process.',
        type: 'HTTP',
      },
      {
        code: 414,
        name: 'URI Too Long',
        description: 'The URI provided was too long for the server to process.',
        type: 'HTTP',
      },
      {
        code: 415,
        name: 'Unsupported Media Type',
        description: 'The media type of the request entity is not supported by the server or resource.',
        type: 'HTTP',
      },
      {
        code: 416,
        name: 'Range Not Satisfiable',
        description: 'The client requested a part of the file the server cannot supply.',
        type: 'HTTP',
      },
      {
        code: 417,
        name: 'Expectation Failed',
        description: 'The server cannot meet the requirements of the Expect request-header field.',
        type: 'HTTP',
      },
      {
        code: 418,
        name: "I'm a teapot",
        description: 'The server refuses to brew coffee with a teapot (RFC 2324, April Fools).',
        type: 'HTTP',
      },
      {
        code: 421,
        name: 'Misdirected Request',
        description: 'The request was directed to a server that cannot produce a response.',
        type: 'HTTP',
      },
      {
        code: 422,
        name: 'Unprocessable Entity',
        description: 'The request was well-formed but cannot be followed due to semantic errors.',
        type: 'HTTP',
      },
      {
        code: 423,
        name: 'Locked',
        description: 'The resource being accessed is locked.',
        type: 'WebDav',
      },
      {
        code: 424,
        name: 'Failed Dependency',
        description: 'The request failed because a previous request failed.',
        type: 'WebDav',
      },
      {
        code: 425,
        name: 'Too Early',
        description: 'The server is unwilling to risk processing a request that might be replayed.',
        type: 'HTTP',
      },
      {
        code: 426,
        name: 'Upgrade Required',
        description: 'The client should switch to a different protocol, such as TLS/1.0.',
        type: 'HTTP',
      },
      {
        code: 428,
        name: 'Precondition Required',
        description: 'The origin server requires the request to be conditional.',
        type: 'HTTP',
      },
      {
        code: 429,
        name: 'Too Many Requests',
        description: 'The user sent too many requests in a given amount of time.',
        type: 'HTTP',
      },
      {
        code: 431,
        name: 'Request Header Fields Too Large',
        description: 'The server is unwilling to process the request because a header field, or all headers together, are too large.',
        type: 'HTTP',
      },
      {
        code: 451,
        name: 'Unavailable For Legal Reasons',
        description: 'The operator has received a legal demand to deny access to a set of resources including the requested one.',
        type: 'HTTP',
      },
    ],
  },
  {
    category: '5xx Server errors',
    codes: [
      {
        code: 500,
        name: 'Internal Server Error',
        description: 'A generic error message given when an unexpected condition was encountered and no more specific message is suitable.',
        type: 'HTTP',
      },
      {
        code: 501,
        name: 'Not Implemented',
        description: 'The server either does not recognize the request method or lacks the ability to fulfill it.',
        type: 'HTTP',
      },
      {
        code: 502,
        name: 'Bad Gateway',
        description: 'The server, while acting as a gateway or proxy, received an invalid response from the upstream server.',
        type: 'HTTP',
      },
      {
        code: 503,
        name: 'Service Unavailable',
        description: 'The server is currently unavailable (due to overload or maintenance).',
        type: 'HTTP',
      },
      {
        code: 504,
        name: 'Gateway Timeout',
        description: 'The server, while acting as a gateway or proxy, did not receive a timely response from the upstream server.',
        type: 'HTTP',
      },
      {
        code: 505,
        name: 'HTTP Version Not Supported',
        description: 'The server does not support the HTTP protocol version used in the request.',
        type: 'HTTP',
      },
      {
        code: 506,
        name: 'Variant Also Negotiates',
        description: 'Transparent content negotiation for the request resulted in a circular reference.',
        type: 'HTTP',
      },
      {
        code: 507,
        name: 'Insufficient Storage',
        description: 'The server is unable to store the representation needed to complete the request.',
        type: 'WebDav',
      },
      {
        code: 508,
        name: 'Loop Detected',
        description: 'The server detected an infinite loop while processing the request.',
        type: 'WebDav',
      },
      {
        code: 510,
        name: 'Not Extended',
        description: 'Further extensions to the request are required for the server to fulfill it.',
        type: 'HTTP',
      },
      {
        code: 511,
        name: 'Network Authentication Required',
        description: 'The client must authenticate to gain network access.',
        type: 'HTTP',
      },
    ],
  },
];
